CREATE TABLE producto(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100)  NOT NULL,
    precio DOUBLE NOT NULL
);

--Insertar datos iniciales
INSERT INTO producto (nombre, precio) VALUES ('Botella de Agua', 9990);
INSERT INTO producto (nombre, precio) VALUES ('Telefono Celular', 100090);
INSERT INTO producto (nombre, precio) VALUES ('Mani con merken', 1000);

COMMIT;